S sushkevich
evgeny-s/tms-graduation-project pull request #3
Opened 2019-04-07 15:04 UTC by s-sushkevich

s-suskevich -> master

2019-04-07 22:16 UTC, evgeny-s requested changes
Check also this file:
~$map.xlsx
Seems like we don't need to add it to the repo..

2019-04-07 22:16 UTC, evgeny-s commented on src/App.js
> +    render() {
Let's move this component to the functional one, since it does not has state.

2019-04-07 22:16 UTC, evgeny-s commented on src/applications/sushkevich/App.js
> +class App extends Component {
Again let's move it to the functional component.

2019-04-07 22:16 UTC, evgeny-s commented on src/applications/sushkevich/components/Map.js
> +        if (this.props.playerLevel === 1 && gameService.isSkill(this.props.map, targetY, targetX)) {
Would be great to use here constant like PLAYER_LEVEL_FIRST instead of magic numbers. Try to avoid magic numbers inside codebase!

2019-04-07 22:16 UTC, evgeny-s commented on src/applications/sushkevich/components/Map.js
> +        if (this.props.playerLevel === 2 && gameService.isCertificate(this.props.map, targetY, targetX)) {
The same

2019-04-07 22:16 UTC, evgeny-s commented on src/applications/sushkevich/components/Map.js
> +                                        return <MapItem
Please, use shorthand arrow function syntax instead of explicit return statement.

2019-04-07 22:16 UTC, evgeny-s commented on src/applications/sushkevich/components/Result.js
> +        }
Formatting needs. Ctrl+L in the phpstorm. (not critical)

2019-04-07 22:16 UTC, evgeny-s commented on src/applications/sushkevich/components/Stats.js
> +    playerStats: PropTypes.object,
can't see getHighScore function here..

2019-04-07 22:16 UTC, evgeny-s commented on src/applications/sushkevich/reducers/gameReducer.js
> +function renderMap(rows, cols) {
I would call this method initializeMap, because it is not a good name - render inside reducers..

2019-04-08 10:45 UTC, s-sushkevich commented on src/applications/sushkevich/components/Result.js
> +        }
Nothing happens after Ctrl+L/Ctrl+Shift+L in WebStorm. Anyway, in case of manual formatting, I can not understand what to change (seems for me like everything is correct).

2019-04-08 11:09 UTC, s-sushkevich commented
All the suggestions are resolved except formatting one (watch the comment in PR suggestions list).

2019-04-08 13:02 UTC, evgeny-s approved these changes
Great job!

2019-04-08 13:02 UTC, evgeny-s commented on src/applications/sushkevich/components/Result.js
> +        }
ok, skip it.

2019-04-08 13:03 UTC, merged