Filippovich
evgeny-s/tms-graduation-project pull request #4
Opened 2019-04-08 20:08 UTC by pyfkin

Finished

2019-04-08 22:34 UTC, evgeny-s requested changes
Please fix listed issues and we're done :)

2019-04-08 22:34 UTC, evgeny-s commented on src/App.js
> +    render()
Let's convert this component to functional one, since it doesn't has state.

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/App.js
> +const mapStateToProps = state => ({
I would split this combined component into the 2 separate components: container and component. Concert separation is nice to have here.

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/src/components/item/index.js
> +    console.log('render');
Please remove this debug.

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/src/components/map/index.js
> +            return false;
I would not use a single like else statement. Use explicit code block instead { ... }

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/src/consts/playerStats.js
> +    '1': {
I would use a constant here, like LEVEL_1, LEVEL_2, it is more explicit.

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/src/containers/map.js
> +            let _x, _y;
Please move this logic to the reducer.

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/src/containers/map.js
> +            switch (side) {
The same - this logic should be inside reducer.

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/src/reducers/gamesReducer.js
> +    health: playerStats['1'].PLAYER_HEALTH,
Again, use a constant for the first level here. Try to avoid magic numbers.

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/src/services/createMapService.js
> +export default class CreateMapService
You can omit class name here and use an anonymous class.

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/src/services/levelService.js
> +            case 1:
Again use constants here.

2019-04-08 22:34 UTC, evgeny-s commented on src/applications/Filippovich/src/services/levelService.js
> +            case 1:
Use constant for the level here also.

2019-04-08 22:36 UTC, evgeny-s requested changes

2019-04-08 22:36 UTC, evgeny-s commented on package.json
> +    "serverFilippovich": "json-server --watch ./src/applications/Filippovich/db/bestPlayers.json --port 3005"
Seems like JSON broken at this line. Please fix

2019-04-09 11:00 UTC, pyfkin commented
Fixed

2019-04-09 15:15 UTC, evgeny-s approved these changes
Well done!

2019-04-09 15:16 UTC, merged